DATASET:
  DATASET_DIR: './dataset'
  TRAINING_DIR: './dataset/train'
  TESTING_DIR: './dataset/val'

  TRAINING_DATASET_LEN: 100000 # Change this to 100k may get better performance
  TESTING_DATASET_LEN: 1000

  CAPTCHA:
    FONT_DIR: './fonts/font1.ttf'
    IMG_HEIGHT: 60
    IMG_WIDTH: 240
    CLASS_NUM: 36
    CHAR_LEN: 6

SOLVER:
  LR: 5.0e-4
  BATCH_SIZE: 256
  EPOCH: 5

LOGGER:
  CHECKPOINT_DIR: './checkpoint'
  LOG_DIR: './logs'
