DATASET:
  DATASET_DIR: './dataset_sssalud'
  TRAINING_DIR: './dataset_sssalud/train'
  TESTING_DIR: './dataset_sssalud/val'

  TRAINING_DATASET_LEN: 80000  # Increase for better performance
  TESTING_DATASET_LEN: 2000

  CAPTCHA:
    FONT_DIR: './fonts/font1.ttf'
    IMG_HEIGHT: 60
    IMG_WIDTH: 240
    CLASS_NUM: 36
    CHAR_LEN: 6

SOLVER:
  LR: 5.0e-4
  BATCH_SIZE: 256
  EPOCH: 8  # More epochs for better convergence

LOGGER:
  CHECKPOINT_DIR: './checkpoint_sssalud'
  LOG_DIR: './logs_sssalud'
